# Generated by Django 2.2.5 on 2020-03-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('script', models.TextField()),
                ('review', models.TextField(help_text='24글자', max_length=24)),
                ('pub_date', models.DateField()),
                ('video_url_1', models.URLField(help_text='예고편', max_length=300)),
                ('video_url_2', models.URLField(help_text='인터뷰', max_length=300)),
                ('video_url_3', models.URLField(help_text='OST', max_length=300)),
                ('video_url_4', models.URLField(help_text='소개영상', max_length=300)),
                ('netflix_url', models.URLField(blank=True, max_length=300, null=True)),
                ('watcha_url', models.URLField(blank=True, max_length=300, null=True)),
                ('google_play_url', models.URLField(blank=True, max_length=300, null=True)),
                ('wavve_url', models.URLField(blank=True, max_length=300, null=True)),
                ('source', models.ManyToManyField(blank=True, to='movies.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
